name: Deploy to WordPress

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build theme
      run: npm run build

    - name: Prepare deployment files
      run: |
        # Create deployment directory
        mkdir -p deploy
        # Copy everything except excluded files
        rsync -av --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='assets/scss' --exclude='package*.json' --exclude='*.md' --exclude='.gitignore' --exclude='.editorconfig' --exclude='bump-version.js' --exclude='deploy' ./ deploy/

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{ secrets.FTP_PORT }} ${{ secrets.FTP_SERVER }} >> ~/.ssh/known_hosts

    - name: Test SFTP connection
      run: |
        echo "Testing SFTP connection..."
        cat > test_batch << EOF
        pwd
        ls
        bye
        EOF
        sftp -P ${{ secrets.FTP_PORT }} -b test_batch ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }}

    - name: Deploy via SFTP
      run: |
        # Create a batch file for SFTP commands
        cat > sftp_batch << EOF
        -mkdir /wp-content
        -mkdir /wp-content/themes
        -mkdir /wp-content/themes/docs-theme
        cd /wp-content/themes/docs-theme
        put -r deploy/* .
        bye
        EOF
        
        # Execute SFTP
        sftp -P ${{ secrets.FTP_PORT }} -b sftp_batch ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }}